name: 'Github Actions Weather Bot'

on:
  push:
    branches:
      - master
  schedule:
    - name: Setup timezone
      uses: zcong1993/setup-timezone@v1.1.1
      with:
        timezone: Asia/Shanghai
    - cron: '0 08 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Install node"
        uses: actions/setup-node@v1
      - name: "Install NPM dependencies"
        run: npm install
      - name: "Run code"
        run: node index.js
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          WEATHER_API_TOKEN: ${{ secrets.WEATHER_API_TOKEN }}